// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1CjB6j9pTrVQSiUd9kW0qUtUGMYH9Kjs',
    appId: '1:470635657912:web:a39092d97339dc5efd924d',
    messagingSenderId: '470635657912',
    projectId: 'usuarios-8e902',
    authDomain: 'usuarios-8e902.firebaseapp.com',
    storageBucket: 'usuarios-8e902.firebasestorage.app',
    measurementId: 'G-QCGH49G7T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8-kAJuq2-GG9ijG2CWwimH21Qd7mQBJw',
    appId: '1:470635657912:android:1e4290037920c00dfd924d',
    messagingSenderId: '470635657912',
    projectId: 'usuarios-8e902',
    storageBucket: 'usuarios-8e902.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOxRAfb2EpH4G3JtigcGR_biMosXzrZUw',
    appId: '1:470635657912:ios:be11001e984fa330fd924d',
    messagingSenderId: '470635657912',
    projectId: 'usuarios-8e902',
    storageBucket: 'usuarios-8e902.firebasestorage.app',
    iosBundleId: 'br.edu.ifsp.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOxRAfb2EpH4G3JtigcGR_biMosXzrZUw',
    appId: '1:470635657912:ios:be11001e984fa330fd924d',
    messagingSenderId: '470635657912',
    projectId: 'usuarios-8e902',
    storageBucket: 'usuarios-8e902.firebasestorage.app',
    iosBundleId: 'br.edu.ifsp.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1CjB6j9pTrVQSiUd9kW0qUtUGMYH9Kjs',
    appId: '1:470635657912:web:d6deec9b6d65447bfd924d',
    messagingSenderId: '470635657912',
    projectId: 'usuarios-8e902',
    authDomain: 'usuarios-8e902.firebaseapp.com',
    storageBucket: 'usuarios-8e902.firebasestorage.app',
    measurementId: 'G-6CPVYLQ02B',
  );

}